export const dictionaries = {
    ru: {
        nav: { how: "Как это работает", features: "Модули", audience: "Кому подойдет", pricing: "Тарифы" },
        common: { waitlist: "В лист ожидания" },
        hero: { badge: "Экономит до 98% времени", title1: "Маркетинговый мозг в кармане", sub: "Загружаете ссылку на сайт или описание бизнеса. Через две минуты получаете результат, на который у агентства уходит неделя.", m1v: "2 мин", m1s: "вместо 1-2 недель", m2v: "10+", m2s: "видов анализов", m3v: "9/10", m3s: "оценка точности", placeholder: "Ваш лучший email", join: "В лист ожидания", already: "С нами уже 2,000+ человек" },
        how: { sub: "Пользовательский путь", title: "Как это работает", s1t: "Загрузка данных", s1d: "Вставьте ссылку на сайт. Или напишите пару слов о вашем бизнесе. Никаких долгих брифов.", s2t: "Выбор задачи", s2d: "Выберите нужную карточку: анализ сайта, разбор конкурентов, аудитория или контент-план.", s3t: "AI-генерация", s3d: "Приложение собирает реальные данные с рынка. Оно пишет понятный отчет с выводами.", s4t: "Экспорт и действие", s4d: "Ваш отчет готов. Скачайте его в PDF. Отправьте команде в удобный рабочий чат." },
        features: { sub: "Что внутри", title: "Модули приложения", f1t: "Анализ сайта", f1d: "Полный UX-разбор, скорость работы и конверсионные точки. Покажем, что сломано и как это починить.", f2t: "Целевая аудитория", f2d: "Составим точные портреты клиентов. Найдем их скрытые боли и подскажем, где их дешевле искать.", f3t: "Анализ конкурентов", f3d: "Изучим предложения соперников по рынку. Найдем их слабые места. Покажем, как вам выделиться.", f4t: "Маркетинговый план", f4d: "Соберем стратегию на три месяца вперед. Распишем нужные каналы, бюджеты и метрики успеха.", f5t: "Тексты и копирайтинг", f5d: "Напишем тексты для лендинга. Адаптируем их под ваш уникальный голос бренда. Никакой во́ды.", f6t: "Рекламные креативы", f6d: "Придумаем идеи для рекламы. Дадим готовые сценарии, хуки и тексты для рекламных сетей.", f7t: "Контент-стратегия", f7d: "Сделаем план публикаций. Придумаем интересные форматы и рубрики для социальных сетей.", f8t: "Email-воронка", f8d: "Напишем логичную цепочку писем. От первого приветствия до финальной продажи. Готовый текст.", f9t: "SEO-аудит", f9d: "Соберем ключевые слова. Проверим структуру и метатеги. Выдадим список правок разработчику.", f10t: "Позиционирование", f10d: "Сформулируем ваше уникальное предложение. Найдем ту самую мысль, которую нужно донести." },
        audience: { sub: "Кому это нужно", title: "Кому поможет MarkIQ", a1t: "Владельцам бизнеса", a1d: "У вас нет маркетолога. Нет времени на метрики. Вы хотите получить результат, а не бесконечный процесс.", a2t: "Фрилансерам", a2d: "Идеальный инструмент для старта с клиентом. Экономьте часы на рутине. Берите дорогие проекты.", a3t: "Стартапам", a3d: "Быстрая проверка бизнес-гипотез. Найдите свою аудиторию без найма дорогого агентства.", a4t: "Рекламным агентствам", a4d: "Автоматизируйте первичные брифы и аудиты. Ускорьте работу всей команды в несколько раз." },
        pricing: { sub: "Бизнес-модель", title: "Тарифы", forever: "навсегда", mo: "в месяц", popular: "Популярный", choose: "Выбрать", p1n: "Free", p1f1: "3 анализа в месяц", p1f2: "3 базовых модуля", p1f3: "PDF-экспорт", p2n: "Pro", p2f1: "Безлимитные анализы", p2f2: "Все 10+ модулей", p2f3: "История проектов", p2f4: "Экспорт в PDF и Notion", p3n: "Agency", p3f1: "До 10 пользователей", p3f2: "Свой логотип на отчетах", p3f3: "API-доступ" },
        waitlist: { title: "Время строить, не анализировать", sub: "Идея проработана. Встаньте в очередь первыми. Рынок не будет ждать." },
        form: { req: "Введите валидный email", roleReq: "Выберите вашу роль", success: "Вы в списке! Мы свяжемся с вами.", error: "Что-то пошло не так. Попробуйте еще раз.", selectMsg: "Кто вы?", r1: "Владелец бизнеса", r2: "Маркетолог / Агентство", r3: "Продакт / Стартап", searching: "Отправка..." },
        footer: { desc: "Быстрые маркетинговые исследования и стратегии с помощью AI", links: "Ссылки", legal: "Правовая информация", privacy: "Политика конфиденциальности", terms: "Пользовательское соглашение", offer: "Публичная оферта", rights: "Все права защищены.", beta: "Ограниченная бета-версия" }
    },
    en: {
        nav: { how: "How it works", features: "Modules", audience: "For whom", pricing: "Pricing" },
        common: { waitlist: "Join waitlist" },
        hero: { badge: "Saves up to 98% of your time", title1: "Marketing brain in your pocket", sub: "Paste a website link or a short business description. Get the results in two minutes that usually take an agency a week.", m1v: "2 min", m1s: "instead of 1-2 weeks", m2v: "10+", m2s: "analysis types", m3v: "9/10", m3s: "accuracy score", placeholder: "Your best email", join: "Join waitlist", already: "Join 2,000+ others" },
        how: { sub: "User Journey", title: "How it works", s1t: "Upload data", s1d: "Paste a link to your website or write a few words about your business. No endless briefs.", s2t: "Select task", s2d: "Choose the exact card you need: website analysis, competitor review, audience, or content plan.", s3t: "AI Generation", s3d: "The app gathers real market data and writes a clear report with actionable insights.", s4t: "Export & Act", s4d: "Your report is ready. Download it as a PDF. Send it to your team in your favorite work chat." },
        features: { sub: "What's inside", title: "Application Modules", f1t: "Website Analysis", f1d: "Full UX review, performance speed, and conversion points. We'll show what's broken and how to fix it.", f2t: "Target Audience", f2d: "We build accurate customer profiles. Find their hidden pain points and see where to acquire them cheaper.", f3t: "Competitor Analysis", f3d: "Study what your market rivals offer. Find their weak spots. See exactly how you can stand out.", f4t: "Marketing Plan", f4d: "Get a 3-month strategic roadmap detailing necessary channels, budgets, and success metrics.", f5t: "Copywriting", f5d: "We'll write your landing page copy adapted to your unique brand voice. No fluff.", f6t: "Ad Creatives", f6d: "Generate fresh advertising ideas. Get ready-to-use scripts, hooks, and copy for ad networks.", f7t: "Content Strategy", f7d: "Create a publication schedule. Come up with engaging formats and recurring topics for social media.", f8t: "Email Funnel", f8d: "We'll write a logical sequence of emails, from the first welcome to the final sale. Ready text.", f9t: "SEO Audit", f9d: "We'll collect keywords, check structure, and provide a list of technical edits for your developer.", f10t: "Positioning", f10d: "Formulate your unique value proposition. Find the exact core message you need to convey." },
        audience: { sub: "Who needs this", title: "Who is MarkIQ for", a1t: "Business Owners", a1d: "You don't have a marketer. No time for metrics. You want results, not an endless process.", a2t: "Freelancers", a2d: "The ideal tool to kickstart client work. Save hours on routine tasks and take on premium projects.", a3t: "Startups", a3d: "Quickly validate business hypotheses. Find your audience without hiring an expensive agency.", a4t: "Ad Agencies", a4d: "Automate initial briefs and audits. Multiply the speed of your entire team." },
        pricing: { sub: "Business Model", title: "Pricing Plans", forever: "forever", mo: "per month", popular: "Popular", choose: "Choose", p1n: "Free", p1f1: "3 analyses per month", p1f2: "3 basic modules", p1f3: "PDF export", p2n: "Pro", p2f1: "Unlimited analyses", p2f2: "All 10+ modules", p2f3: "Project history", p2f4: "Export to PDF & Notion", p3n: "Agency", p3f1: "Up to 10 users", p3f2: "Custom branding on reports", p3f3: "API access" },
        waitlist: { title: "Time to build, not analyze", sub: "The idea is mapped out. Get in line first. The market won't wait." },
        form: { req: "Enter a valid email", roleReq: "Select your role", success: "You're on the list! We'll be in touch.", error: "Something went wrong. Please try again.", selectMsg: "Who are you?", r1: "Business Owner", r2: "Marketer / Agency", r3: "Product / Startup", searching: "Sending..." },
        footer: { desc: "Fast marketing research and strategies powered by AI", links: "Links", legal: "Legal", privacy: "Privacy Policy", terms: "Terms of Service", offer: "Public Offer", rights: "All rights reserved.", beta: "Limited Beta" }
    }
};

export type Locale = keyof typeof dictionaries;
